---
- name: Create VMExper directory and copy files
  hosts: solid_servers
  become: true
  tasks:
    - name: Create directory if it doesn't exist
      file:
        path: /usr/local/50VMExper
        state: directory
      register: dir_created

    - name: Copy directory from local to remote
      copy:
        src:  "/Users/ragab/ESPRESSO\ Project/Impementations/GithubRepo/ESPRESSO/Searcher"
        dest: /usr/local/50VMExper/
        remote_src: yes
      when: dir_created.changed
