---
- name: Install Solid Community Server
  hosts: solid_servers
  #hosts:localhost
  #connection: local
  become: yes

  vars:
    github_url: https://MohamedRagabAnas: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@github.com/espressogroup/ESPRESSO.git
    project_path: /usr/local/ESPRESSO

  tasks:
    - name: Update package cache
      dnf:
        update_cache: yes

    - name: Install node.js and npm
      dnf:
        name:
          - nodejs
          - npm
        state: present

#    - name: Install Node.js
#      dnf:
#        name: nodejs:16
#        state: present


    - name: Install gtop
      npm:
        name: gtop
        global: true

    # Clone the project if it doesn't exist
    - name: Clone GitHub project
      git:
        repo: "{{ github_url }}"
        dest: "{{ project_path }}"
        version: main
      when: not ansible_local.git_installed|default(false)

    # Pull the latest changes if the project already exists
    - name: Pull latest changes from GitHub project
      git:
        repo: "{{ github_url }}"
        dest: "{{ project_path }}"
        version: main
        update: yes
      when: ansible_local.git_installed|default(false)


    - name: Install Solid Community Server
      npm:
        name: "@solid/community-server"
        global: yes
