- name: Run Searcher App
  hosts: solid_servers
  become: yes

  vars:
    script_directory: /usr/local/Reza-WorkSpace/BuildGaian/SolidSearch_StandAlone/

  tasks:
    - name: Run server.js script
      become: true
      shell: node --max-old-space-size=8000 /usr/local/Reza-WorkSpace/BuildGaian/SolidSearch_StandAlone/server.js
      async: 3600
      poll: 0
      register: script_task

    - name: Wait for script to finish
      become: true
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 8080
        state: started
      when: script_task is defined and script_task.finished

    - name: Print script status
      debug:
        msg: "server.js script is running on {{ inventory_hostname }} with PID {{ script_task.ansible_pid }}"
      when: script_task is defined and script_task.finished and script_task.status == 'SUCCESS'
