- name: Stopping Gaian Servers
  hosts: solid_servers
  become: yes

  tasks:
    # Find the process ID running on port 6414
    - name: Find process ID
      become: true
      shell: "lsof -t -i :6414"
      register: process_id
      ignore_errors: yes

    # Stop the process
    - name: Stop the process
      become: true
      shell: "kill -9 {{ process_id.stdout }}"
      when: process_id.stdout is defined
